# Generated by Django 5.0.7 on 2024-10-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_usercart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='pizzas',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='models.pizza'),
            preserve_default=False,
        ),
    ]
