# Generated by Django 5.0.7 on 2024-10-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_cartitems_pizzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.usercart')),
                ('pizzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.pizza')),
            ],
        ),
    ]
