# Generated by Django 5.0.7 on 2024-10-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_delete_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizzas',
        ),
    ]
