# Generated by Django 5.0.7 on 2024-10-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_delete_pizzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.FileField(default=None, null=True, upload_to='images')),
                ('descrip', models.CharField(max_length=100, null=True)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.usercart')),
                ('pizzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.pizzas')),
            ],
        ),
    ]
