# Generated by Django 5.0.7 on 2024-10-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_pizzas_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Pizzas',
        ),
        migrations.DeleteModel(
            name='Usercart',
        ),
    ]
